# Generated by Django 4.2.11 on 2024-04-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userAccount", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[("A", "admin"), ("C", "chef"), ("S", "subscriber")],
                max_length=1,
                unique=True,
            ),
        ),
    ]
