# Generated by Django 4.1 on 2024-04-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAccount", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[("C", "chef"), ("A", "admin"), ("S", "subscriber")],
                max_length=1,
                unique=True,
            ),
        ),
    ]
