# Generated by Django 4.2.11 on 2024-04-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userAccount", "0002_alter_role_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[("A", "admin"), ("S", "subscriber"), ("C", "chef")],
                max_length=1,
                unique=True,
            ),
        ),
    ]
