# Generated by Django 4.2.11 on 2024-04-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userAccount", "0003_alter_role_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[("C", "chef"), ("S", "subscriber"), ("A", "admin")],
                max_length=1,
                unique=True,
            ),
        ),
    ]
