# Generated by Django 5.0.3 on 2024-04-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userAccount", "0014_alter_chefsubscription_time_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chefsubscription",
            name="time_unit",
            field=models.CharField(
                choices=[("M", "Month"), ("W", "Week"), ("Y", "Year")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="measurement",
            field=models.CharField(
                choices=[
                    ("tbsp", "tablespoon"),
                    ("ml", "milliliter"),
                    ("gal", "gallon"),
                    ("qt", "quart"),
                    ("g", "gram"),
                    ("fl oz", "fluid ounce"),
                    ("pt", "pint"),
                    ("na", "none"),
                    ("tsp", "teaspoon"),
                    ("cup", "cup"),
                    ("oz", "ounce"),
                    ("L", "liter"),
                    ("kg", "kilogram"),
                    ("lb", "pound"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[("C", "chef"), ("A", "admin"), ("S", "subscriber")],
                max_length=1,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitesubscription",
            name="time_unit",
            field=models.CharField(
                choices=[("M", "Month"), ("W", "Week"), ("Y", "Year")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="platform",
            field=models.CharField(
                choices=[
                    ("Y", "YouTube"),
                    ("I", "Instagram"),
                    ("F", "Facebook"),
                    ("TW", "Twitter"),
                    ("S", "Snapchat"),
                    ("TK", "TikTok"),
                ],
                max_length=2,
            ),
        ),
    ]
