# Generated by Django 4.2.11 on 2024-04-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('ml', 'milliliter'), ('na', 'none'), ('slice', 'slice'), ('pt', 'pint'), ('gal', 'gallon'), ('qt', 'quart'), ('tsp', 'teaspoon'), ('cup', 'cup'), ('fl oz', 'fluid ounce'), ('lb', 'pound'), ('g', 'gram'), ('oz', 'ounce'), ('kg', 'kilogram'), ('slices', 'slices'), ('tbsp', 'tablespoon'), ('L', 'liter')], max_length=15),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('F', 'Facebook'), ('I', 'Instagram'), ('TW', 'Twitter'), ('S', 'Snapchat'), ('Y', 'YouTube'), ('TK', 'TikTok')], max_length=2),
        ),
    ]
