# Generated by Django 4.2.11 on 2024-04-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('L', 'liter'), ('qt', 'quart'), ('gal', 'gallon'), ('tbsp', 'tablespoon'), ('fl oz', 'fluid ounce'), ('tsp', 'teaspoon'), ('oz', 'ounce'), ('pt', 'pint'), ('lb', 'pound'), ('cup', 'cup'), ('ml', 'milliliter'), ('na', 'none'), ('kg', 'kilogram'), ('g', 'gram')], max_length=15),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('TW', 'Twitter'), ('I', 'Instagram'), ('Y', 'YouTube'), ('S', 'Snapchat'), ('TK', 'TikTok'), ('F', 'Facebook')], max_length=2),
        ),
    ]
