# Generated by Django 4.2.11 on 2024-04-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='food',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('g', 'gram'), ('kg', 'kilogram'), ('tsp', 'teaspoon'), ('cup', 'cup'), ('gal', 'gallon'), ('ml', 'milliliter'), ('pt', 'pint'), ('qt', 'quart'), ('fl oz', 'fluid ounce'), ('na', 'none'), ('oz', 'ounce'), ('lb', 'pound'), ('tbsp', 'tablespoon'), ('L', 'liter')], max_length=15),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('I', 'Instagram'), ('S', 'Snapchat'), ('TW', 'Twitter'), ('TK', 'TikTok'), ('F', 'Facebook'), ('Y', 'YouTube')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
