# Generated by Django 4.2.11 on 2024-04-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0003_chefprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('kg', 'kilogram'), ('g', 'gram'), ('na', 'none'), ('ml', 'milliliter'), ('L', 'liter'), ('cup', 'cup'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('pt', 'pint'), ('qt', 'quart'), ('fl oz', 'fluid ounce'), ('lb', 'pound'), ('oz', 'ounce'), ('gal', 'gallon')], max_length=15),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('TK', 'TikTok'), ('F', 'Facebook'), ('Y', 'YouTube'), ('TW', 'Twitter'), ('I', 'Instagram'), ('S', 'Snapchat')], max_length=2),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.TextField(),
        ),
    ]
