# Generated by Django 4.2.11 on 2024-05-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeApp", "0003_alter_ingredient_measurement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="measurement",
            field=models.CharField(
                choices=[
                    ("kg", "kilogram"),
                    ("L", "liter"),
                    ("oz", "ounce"),
                    ("tsp", "teaspoon"),
                    ("tbsp", "tablespoon"),
                    ("qt", "quart"),
                    ("slices", "slices"),
                    ("gal", "gallon"),
                    ("fl oz", "fluid ounce"),
                    ("lb", "pound"),
                    ("ml", "milliliter"),
                    ("na", "none"),
                    ("pt", "pint"),
                    ("slice", "slice"),
                    ("cup", "cup"),
                    ("g", "gram"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="platform",
            field=models.CharField(
                choices=[
                    ("I", "Instagram"),
                    ("F", "Facebook"),
                    ("TW", "Twitter"),
                    ("S", "Snapchat"),
                    ("TK", "TikTok"),
                    ("Y", "YouTube"),
                ],
                max_length=2,
            ),
        ),
    ]
