# Generated by Django 4.2.11 on 2024-04-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0003_alter_ingredient_food_alter_ingredient_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='*'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('na', 'none'), ('tsp', 'teaspoon'), ('qt', 'quart'), ('pt', 'pint'), ('oz', 'ounce'), ('gal', 'gallon'), ('lb', 'pound'), ('kg', 'kilogram'), ('L', 'liter'), ('fl oz', 'fluid ounce'), ('cup', 'cup'), ('g', 'gram'), ('tbsp', 'tablespoon'), ('ml', 'milliliter')], max_length=15),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('TW', 'Twitter'), ('F', 'Facebook'), ('TK', 'TikTok'), ('Y', 'YouTube'), ('S', 'Snapchat'), ('I', 'Instagram')], max_length=2),
        ),
    ]
