# Generated by Django 4.2.11 on 2024-04-22 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipeApp', '0004_alter_ingredient_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('ml', 'milliliter'), ('oz', 'ounce'), ('L', 'liter'), ('fl oz', 'fluid ounce'), ('gal', 'gallon'), ('cup', 'cup'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('qt', 'quart'), ('pt', 'pint'), ('kg', 'kilogram'), ('na', 'none'), ('lb', 'pound'), ('g', 'gram')], max_length=15),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='chef',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('Y', 'YouTube'), ('I', 'Instagram'), ('F', 'Facebook'), ('TW', 'Twitter'), ('TK', 'TikTok'), ('S', 'Snapchat')], max_length=2),
        ),
    ]
