# Generated by Django 4.2.11 on 2024-04-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0004_recipe_description_alter_ingredient_measurement_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='instruction_number',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('gal', 'gallon'), ('oz', 'ounce'), ('ml', 'milliliter'), ('tbsp', 'tablespoon'), ('cup', 'cup'), ('kg', 'kilogram'), ('tsp', 'teaspoon'), ('pt', 'pint'), ('qt', 'quart'), ('lb', 'pound'), ('na', 'none'), ('g', 'gram'), ('fl oz', 'fluid ounce'), ('L', 'liter')], max_length=15),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('F', 'Facebook'), ('S', 'Snapchat'), ('I', 'Instagram'), ('TK', 'TikTok'), ('TW', 'Twitter'), ('Y', 'YouTube')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_number',
        ),
    ]
