# Generated by Django 4.2.11 on 2024-04-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0005_alter_ingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('cup', 'cup'), ('tsp', 'teaspoon'), ('qt', 'quart'), ('ml', 'milliliter'), ('na', 'none'), ('oz', 'ounce'), ('lb', 'pound'), ('L', 'liter'), ('tbsp', 'tablespoon'), ('fl oz', 'fluid ounce'), ('pt', 'pint'), ('kg', 'kilogram'), ('gal', 'gallon'), ('g', 'gram')], max_length=15),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('F', 'Facebook'), ('S', 'Snapchat'), ('TW', 'Twitter'), ('I', 'Instagram'), ('Y', 'YouTube'), ('TK', 'TikTok')], max_length=2),
        ),
    ]
