# Generated by Django 4.2.11 on 2024-04-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0006_ingredient_order_alter_ingredient_measurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='order',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('oz', 'ounce'), ('tbsp', 'tablespoon'), ('g', 'gram'), ('fl oz', 'fluid ounce'), ('L', 'liter'), ('kg', 'kilogram'), ('na', 'none'), ('ml', 'milliliter'), ('qt', 'quart'), ('pt', 'pint'), ('tsp', 'teaspoon'), ('lb', 'pound'), ('gal', 'gallon'), ('cup', 'cup')], max_length=15),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('F', 'Facebook'), ('S', 'Snapchat'), ('TW', 'Twitter'), ('Y', 'YouTube'), ('TK', 'TikTok'), ('I', 'Instagram')], max_length=2),
        ),
    ]
