# Generated by Django 4.2.11 on 2024-04-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0007_remove_ingredient_order_alter_ingredient_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instruction',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('qt', 'quart'), ('na', 'none'), ('kg', 'kilogram'), ('fl oz', 'fluid ounce'), ('pt', 'pint'), ('tsp', 'teaspoon'), ('g', 'gram'), ('L', 'liter'), ('gal', 'gallon'), ('ml', 'milliliter'), ('oz', 'ounce'), ('tbsp', 'tablespoon'), ('cup', 'cup'), ('lb', 'pound')], max_length=15),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('I', 'Instagram'), ('TW', 'Twitter'), ('TK', 'TikTok'), ('F', 'Facebook'), ('Y', 'YouTube'), ('S', 'Snapchat')], max_length=2),
        ),
    ]
