# Generated by Django 4.2.11 on 2024-04-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0009_alter_ingredient_options_alter_instruction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkedrecipes',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('na', 'none'), ('gal', 'gallon'), ('g', 'gram'), ('tbsp', 'tablespoon'), ('ml', 'milliliter'), ('slices', 'slices'), ('oz', 'ounce'), ('slice', 'slice'), ('pt', 'pint'), ('qt', 'quart'), ('kg', 'kilogram'), ('lb', 'pound'), ('fl oz', 'fluid ounce'), ('cup', 'cup'), ('L', 'liter'), ('tsp', 'teaspoon')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('F', 'Facebook'), ('TW', 'Twitter'), ('I', 'Instagram'), ('Y', 'YouTube'), ('S', 'Snapchat'), ('TK', 'TikTok')], max_length=2),
        ),
        migrations.AddField(
            model_name='bookmarkedrecipes',
            name='recipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recipeApp.recipe'),
            preserve_default=False,
        ),
    ]
