# Generated by Django 4.2.11 on 2024-04-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0010_remove_bookmarkedrecipes_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_parent',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('slices', 'slices'), ('slice', 'slice'), ('tbsp', 'tablespoon'), ('qt', 'quart'), ('gal', 'gallon'), ('tsp', 'teaspoon'), ('g', 'gram'), ('na', 'none'), ('pt', 'pint'), ('ml', 'milliliter'), ('fl oz', 'fluid ounce'), ('oz', 'ounce'), ('kg', 'kilogram'), ('cup', 'cup'), ('lb', 'pound'), ('L', 'liter')], max_length=15),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('TW', 'Twitter'), ('F', 'Facebook'), ('Y', 'YouTube'), ('TK', 'TikTok'), ('S', 'Snapchat'), ('I', 'Instagram')], max_length=2),
        ),
    ]
