# Generated by Django 4.2.11 on 2024-04-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0011_remove_comment_comment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('lb', 'pound'), ('tsp', 'teaspoon'), ('L', 'liter'), ('na', 'none'), ('qt', 'quart'), ('kg', 'kilogram'), ('slices', 'slices'), ('pt', 'pint'), ('fl oz', 'fluid ounce'), ('tbsp', 'tablespoon'), ('cup', 'cup'), ('slice', 'slice'), ('gal', 'gallon'), ('oz', 'ounce'), ('g', 'gram'), ('ml', 'milliliter')], max_length=15),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('S', 'Snapchat'), ('TW', 'Twitter'), ('TK', 'TikTok'), ('I', 'Instagram'), ('Y', 'YouTube'), ('F', 'Facebook')], max_length=2),
        ),
    ]
