# Generated by Django 4.2.11 on 2024-04-22 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0012_chefprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='chef',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='chef_prof',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recipeApp.chefprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('pt', 'pint'), ('cup', 'cup'), ('g', 'gram'), ('oz', 'ounce'), ('tbsp', 'tablespoon'), ('na', 'none'), ('slice', 'slice'), ('fl oz', 'fluid ounce'), ('slices', 'slices'), ('lb', 'pound'), ('tsp', 'teaspoon'), ('kg', 'kilogram'), ('gal', 'gallon'), ('ml', 'milliliter'), ('qt', 'quart'), ('L', 'liter')], max_length=15),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('TK', 'TikTok'), ('S', 'Snapchat'), ('Y', 'YouTube'), ('I', 'Instagram'), ('F', 'Facebook'), ('TW', 'Twitter')], max_length=2),
        ),
    ]
