# Generated by Django 4.2.11 on 2024-04-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0013_remove_socialmedia_chef_socialmedia_chef_prof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('fl oz', 'fluid ounce'), ('gal', 'gallon'), ('g', 'gram'), ('tsp', 'teaspoon'), ('slice', 'slice'), ('pt', 'pint'), ('qt', 'quart'), ('na', 'none'), ('ml', 'milliliter'), ('kg', 'kilogram'), ('lb', 'pound'), ('slices', 'slices'), ('oz', 'ounce'), ('tbsp', 'tablespoon'), ('cup', 'cup'), ('L', 'liter')], max_length=15),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('TK', 'TikTok'), ('I', 'Instagram'), ('F', 'Facebook'), ('S', 'Snapchat'), ('TW', 'Twitter'), ('Y', 'YouTube')], max_length=2),
        ),
    ]
