# Generated by Django 4.2.11 on 2024-04-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscriptiontosite_stripe_price_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptiontosite",
            name="stripe_price_id",
        ),
        migrations.AddField(
            model_name="sitesubscription",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="chefsubscription",
            name="time_unit",
            field=models.CharField(
                choices=[("Y", "Year"), ("M", "Month"), ("W", "Week")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="sitesubscription",
            name="time_unit",
            field=models.CharField(
                choices=[("Y", "Year"), ("M", "Month"), ("W", "Week")], max_length=10
            ),
        ),
    ]
