# Generated by Django 4.1 on 2024-04-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chefsubscription",
            name="time_unit",
            field=models.CharField(
                choices=[("M", "Month"), ("W", "Week"), ("Y", "Year")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="sitesubscription",
            name="time_unit",
            field=models.CharField(
                choices=[("M", "Month"), ("W", "Week"), ("Y", "Year")], max_length=10
            ),
        ),
    ]
