# Generated by Django 4.2.11 on 2024-04-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_chefsubscription_time_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefsubscription',
            name='time_unit',
            field=models.CharField(choices=[('Y', 'Year'), ('W', 'Week'), ('M', 'Month')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sitesubscription',
            name='time_unit',
            field=models.CharField(choices=[('Y', 'Year'), ('W', 'Week'), ('M', 'Month')], max_length=10),
        ),
    ]
